name: deployment of exercise
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v4
        with:
          node-version: 20
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      # - name: Init Lint
      # #   run: npm init @eslint/config
      # - name: Run lint
      #   run: npm run lint
      - name: Run Tests
        run: npm test
  deployment:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Download Code
        uses: actions/checkout@v4
        with:
          node-version: 20
      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Deploy
        run: npm build